### PR TITLE
Return container Ip

### PR DESCRIPTION
**Pull request by gbrian**

### CODE REVIEW

**Comment by m1k1o** [comment]
Why is an IP needed? Docker has working internal DNS. When addressing container name, that is by default `<InstanceName>-<roomName>` (what is by default `neko-rooms-<roomName>`) it resolves to internal IP. Would not be more flexible to have container name there? Or what is the usecase for this IP?

**Comment by gbrian** [comment]
You are right, I'm configuring traefik http provider for the exposed ports so having the IP allows me to create the "service" url. Container name is neko-room's dependand as I can't define it on the configuration but defiitely is another approach.

**Comment by m1k1o** [comment]
You can use first 12 characters from container ID instead. That works as well as DNS. Maybe we should truncate that in neko rooms so that it can be used as DNS.

**Comment by gbrian** [comment]
Cool moved to the ID-12 name. Thanks!

**Pull request closed without merging**
