### PR TITLE
Add missing Neko variants to drop-down menu

### PR DESCRIPTION
**Pull request by whalehub**
This pull request adds the other tags of the Neko image to the drop-down menu.

### CODE REVIEW

**Comment by m1k1o** [comment]
Thanks!

With VLC it would be nice to have ability to mount custom media directroy. Also maybe storing browser profiles.

And maybe specifying own ENV variables could be beneficial:
- `VLC_MEDIA` what specifies directory / initial media that should be played
- `NEKO_VNC_URL` for vncviewer, to set remote URL to connect to.

I should add this to roadmap.

**Comment by whalehub** [comment]
@m1k1o Yeah, that sounds good to me. It'd probably be best to allow user input for those options in the expert settings section.

Btw, can you enable automated builds for this repository on Docker Hub?

**Comment by m1k1o** [comment]
Yes, but my only concern is about security with custom volumes. That could be potemtially abused to mount any directory on host, so it needs to be good secured.

Yes, it is enabled, but docker-hub seems to be really slow today:
image

**Comment by whalehub** [comment]
@m1k1o Good point, I hadn't considered that. Maybe users could be offered a list of directories to choose from like with the different tags. This list of directories could be controlled by the administrator using environment variables on the Neko Rooms container, e.g. `NEKO_ROOMS_DIRECTORY_WHITELIST`.

**Comment by m1k1o** [comment]
Yeah, that would go. Having pool of directories that can be used.

But if we want to save user profiles of multiple instances, then there would need to be created subdirectories. And then allowing only some regex for folder names e.g. `A-Za-z0-9-_.` so that no path traversal could take place. That would probably need additional logic -> data manager, where user could manage data. It must be also ensured, that one data folder is mounted maximum to 1 container at a time.

Seems to be more complex, I am generally open for ideas.

**Pull request merged**
